---
- name: load configuration from file
  include_role:
    name: privateip.eos
    tasks_from: load_config
  vars:
    config_file: "{{ item }}"
    eos_config_replace: "{{ replace | default(False) }}"
  with_first_found:
    - files:
        - "{{ src }}"
      paths:
        - "templates/eos/{{ inventory_hostname_short }}"
        - "templates/eos/default"
