---
- hosts: all
  gather_facts: no

  vars:
    dest_path: "/opt/network"
    dest_file: "{{ inventory_hostname_short }}.cfg"

  tasks:
    - name: backup active configuration from devices
      include_role:
        name: ansible-network.config_manager
        tasks_from: get

    - name: write configuration to ansible controller
      copy:
        content: "{{ configuration }}"
        dest: "{{ dest_patht }}/{{ dest_file }}"
