---
- hosts: all
  gather_facts: no

  tasks:
    - name: get active configuration from network device
      include_tasks: "includes/{{ ansible_network_os }}/backup_config.yaml"

    - name: write configuration to ansible controller
      copy:
        content: "{{ configuration }}"
        dest: "/opt/network/{{ inventory_hostname_short }}.cfg"
