---
- hosts: all
  gather_facts: no

  tasks:
    - name: replace device configuration with default
      include_role:
        name: "{{ ansible_network_provider }}"
        tasks_from: load_config
      vars:
        config_file: "files/base/{{ inventory_hostname_short }}.cfg"
        replace: yes
