---
- hosts: all
  gather_facts: no

  tasks:
    - name: check if old checkpoint file exists on device
      cli:
        command: dir
      register: ios_dir_listing

    - name: remove old checkpoint file from device
      cli:
        command: "delete /force flash://{{ ios_config_checkpoint_filename }}"
      when: ios_config_checkpoint_filename in ios_dir_listing.stdout

    - name: checkpoint existing configuration for rollback
      ios_command_local:
        commands:
          - command: "copy running-config flash:{{ ios_config_checkpoint_filename }}"
            prompt: ["? "]
            answer: "{{ ios_config_checkpoint_filename }}"
