---
- hosts: all
  gather_facts: no

  tasks:
    - name: load configuration from text
      include_role:
        name: ansible-network.config_manager_devel
        tasks_from: load
      vars:
        config_manager_scm_url: https://github.com/privateip/infra_configs
