---
- hosts: all
  gather_facts: no

  tasks:
    - name: load configuration from file
      include_role:
        name: privateip.eos
        tasks_from: load_config
      vars:
        config_file: "{{ item }}"
      with_first_found:
        - files:
            - "{{ src }}"
          paths:
            - "files/eos/{{ inventory_hostname_short }}"
            - "files/eos/default"

