---
- hosts: all
  gather_facts: no

  roles:
    - name: privateip.eos
      function: load_config
      config_file: "{{ item }}"
      with_first_found:
        - files:
            - "{{ src }}"
          paths:
            - "files/eos/{{ inventory_hostname_short }}"
            - "files/eos/default"

