---
- hosts: all
  gather_facts: no

  tasks:
    - name: create temp working dir
      tempfile:
        state: directory
      register: temp_working_dir
      changed_when: false
      run_once: yes

    - block:
      - name: checkout scm templates project
        git:
          repo: "{{ scm_url }}"
          dest: "{{ temp_working_dir.path }}"
        changed_when: false
        run_once: yes

      - name: load template configuration onto remote device
        include_role:
          name: ansible-network.config_manager
          tasks_from: load
        loop_control:
          loop_var: config_manager_file
        with_first_found:
          - files: "{{ template_name }}"
            paths:
              - "{{ temp_working_dir.path }}/{{ ansible_network_os }}/{{ inventory_hostname_short }}"
              - "{{ temp_working_dir.path }}/{{ ansible_network_os }}/default"
              - "{{ temp_working_dir.path }}/default"
      always:
        - name: remove temp working dir
          file:
            path: "{{ temp_working_dir.path }}"
            state: absent
          run_once: yes
          changed_when: false
