---
- hosts: all
  gather_facts: no

  tasks:
    - name: replace device configuration with default
      include_role:
        name: ansible-network.config_manager
        tasks_from: load
      vars:
        config_manager_scm_url: https://github.com/privateip/infra_configs
        config_manager_replace: yes
