---
- name: "ios: get the current active configuration from target device"
  cli:
    command: show running-config
  register: configuration

- name: set the configuration fact
  set_fact:
    configuration: "{{ configuration.stdout }}"
